# This workflow will do a clean installation of NodeJS and project dependencies,
# build the source code and run unit tests on each Git push or pull operation.
# For more information see:
#   https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# The status of each execution of this workflow will be displayed under this
# label in the GitHub dashboard for the repository.
name: Node.js Push/Pull

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        cache: 'npm'
    - run: echo '//npm.pkg.github.com/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}' >> .npmrc
    - run: npm install
    - run: npm test